---
title: "Identify Latent Dimensions of Digital Engagement and Social Capital using the 2024 GSS"
subtitle: "Social Survey Analytics Using MCA"
author: "Matthew Beck<br>Min Zhong<br>Kaitlin Kosko<br>Advisor: Dr. Cohen"
date: '`r Sys.Date()`'
format:
  html:
    code-fold: true
course: Capstone Projects in Data Science
bibliography: references.bib # file contains bibtex for references
#always_allow_html: true # this allows to get PDF with HTML features
self-contained: true
execute: 
  warning: false
  message: false
editor: 
  markdown: 
    wrap: 72
---

Slides: [slides.html](slides.html){target="_blank"} ( Go to `slides.qmd`
to edit)


## Introduction

Our project uses the methodology of Multiple Correspondence Analysis (MCA) in order to perform an exploratory analysis on data derived from the General Social Survey examining the topic of digital inequality.
Dimensionality reduction has been a strategy used by scientists as a means of exploratory data analysis. This allows scientists to visually analyze high-dimensional data that would otherwise be difficult to interpret, thereby recognizing associations between variables. One of the most prominent methods for this is Principal Component Analysis, or PCA, which identifies linear combinations of features which maximize variance.

However, a limitation of PCA is that it only can be used on quantitative, numeric data. For datasets with categorical data, Multiple Component Analysis has been developed. One area in which been able to use MCA is in social scientific fields like sociology, psychology, and political science, especially in the analysis of social surveys which use categorical responses to questions, including yes/no questions and so-called ‘Likert scale’ questions, which ask the respondent to answer in a range from, for example, “strongly disagree” to “strongly agree”. One particular example of such a survey is the General Social Survey, administered by NORC. This is the largest such survey in the United States and has been administered for decades to a representative sample of US citizens. The GSS and other such large surveys are perfect for data mining and exploratory data analysis because of their large sample size and the large variety of questions asked on different topics which researchers can use to discover connections between phenomena and underlying patterns of social activity.

In particular, we will be using MCA analysis on the GSS to examine the effects of digital technology on social behavior. In the past decades, digital technology entered into the home, becoming general purpose, woven into everyday life. It has become an integral part of individual life and has changed how people work, study, communicate and participate in society. Because of this important role, it has been discussed through different perspectives. Early studies discussed the “digital divide,” which examines the question of internet access. Recently, research has become broader, expanding to the concept of “digital capital,” a concept which includes digital skills, educational background, and the ability to benefit from online resources (@lybeckDigitalDivideDigital2024). As a result, simple connectivity is no longer sufficient to explain digital inequality; it is a multidimensional concept that involves access, usage patterns, and digital outcomes（@reddickUnderstandingLevelsDigital2024）.

Recent researches suggests that individuals would like to participate in a variety of online activities if they have higher digital capital (@ruiuDigitalCapitalOnline2020). Individuals who shows less online activity usually have lower digital skills, even if they have access to digital technologies. These studies suggest that online participation is associated with broader patterns rather than separate and unrelated behaviors. Meanwhile, Social capital is a complex concept that cannot be measured by a single variable. It has long been discussed by sociologists and it refers to the resources and benefits individuals gain through social networks, community involvement, civic participation, and trust-based relationships. Previous studies have applied principal component analysis(PCA) to identify underlying dimensions of social capital by using multiple survey indicators (@gannonSocialCapitalExploring2020). These approaches suggest that observed measures of social participation and social connectedness may reflect underlying latent dimensions of social capital. 

In this study, we will use data from the 2024 General Social Survey (GSS) to examine whether the association of digital engagement and social capital can be explained through a smaller number of underlying dimensions. Considering that many selected variables are categorical, we apply Multiple Correspondence Analysis (MCA) to identify latent dimensions. The study aims to better understand how these concepts are related in contemporary American society.

## Methods

## Analysis and Results

### Data Exploration and Visualization

### Modeling and Results


### Conclusion


## References
